# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8bcb1b453ee64b2c44f47ec9c436279b73c46658aa09c2a43796de5e28b086422e738817e8705b8192c816ee473ee4e964e459ca2b13db44b62a752bb2351c4a

test:
  secret_key_base: 917cb9740ebe08c3e72da70524f5947d78c7f52022408468cb63e531f7b88ee995cc33688286b33366a62595fff13a300364a045782fc13be00c9733d85d3b02

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
